### ISSUE TITLE
Donation: 16552 from ALNjCMdjXuo1y7PgcGGcexNMAcRFSmN9kY

### ISSUE THREAD

**Issue by ksteigerwald** [coranos/coranos.github.io#1]
Hello, 

I believe my NEO coin was accidentally shipped to you. Yesterday I attempted to send 121 NEO to my bittrex wallet from my desktop NEON wallet. If you have access to these funds, would it be possible you could return them. The amount of coin was significant to me and would really mean the world if it could some how be returned. 

I am happy to provide whatever proof necessary to confirm I was the author of the transaction. 

Issuing Wallet: APPwgkCiCuVSdhrrXU51xaXnzZH9p82Sqg

Kindest regards,
Kris

**Comment by coranos** [comment]
I don't see a donation in my wallet for 121 neo.

Neotracker says you sent it to ALNjCMdjXuo1y7PgcGGcexNMAcRFSmN9kY.

My donation address is APMyYHutJZsZVWAQRe9h4eVrzzD3HLroQW.

Where do you see my donation address as ALNjCMdjXuo1y7PgcGGcexNMAcRFSmN9kY?

**Comment by coranos** [comment]
https://neotracker.io/tx/cab67fbbeb7821b1587d39db7d4316172438522b99569d25461ae235bc5fd562

**Comment by ksteigerwald** [comment]
I don't... it's listed on your github page, so hoping maybe you might know something. I am not certain what your pages is targeted for. It was referred to me by another. 

Regards

**Comment by coranos** [comment]
It's listed on my page that lists all addresses.

I don't have access to the funds at the addresses.

**Comment by ksteigerwald** [comment]
Ok... Sorry to bother. Closing this issue :/
