### ISSUE TITLE
We should prevent creating NEO wallets without `BIP39 Mnemonic`

### ISSUE THREAD

**Issue by ArtemBernatskyy** [coranos/coranos.github.io#3]
When we are creating NEO wallets without `BIP39 Mnemonic` we are always getting same addresses.
 
I know that there are couple of people who have already registered wallets in that way.
I think it is dangerous, contact me for further proofs.

**Comment by coranos** [comment]
You say several people have registered wallets with the address Aar2LbR3QqK5B1QXjGSpEKfJ9qLwqh971W ?

There are zero transactions at that address.

https://neotracker.io/address/Aar2LbR3QqK5B1QXjGSpEKfJ9qLwqh971W

If people are using my *recovery site* to generate *new wallets* they are using it incorrectly.

**Comment by ArtemBernatskyy** [comment]
Yes, exactly, i know people that did that. Plz add validation for empty seed phrase, thx.

**Comment by coranos** [comment]
please prove to me that people did that, by showing me one account that did.

**Comment by ArtemBernatskyy** [comment]
Give me plz your email, or email me (on my profile there is an email), i can't do it in public.

**Comment by coranos** [comment]
Show the NEO account in a public NEO block tracker as I have done above.

**Comment by coranos** [comment]
Let me be precise in why I'm asking you to do it publicly.

You said that someone generated an address putting in all blanks.

I went and generated an address and put in all blanks, and it is the one listed above, which has no NEO in it.

Now if you're talking about some other address, some other blockchain other than NEO, then you are talking about someone else's website, and not mine.
